/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  documentationSidebar: [
    "intro",
    "getting-started",
    {
      type: 'category',
      label: 'Use Cases',
      items: [{ type: "autogenerated", dirName: "use-cases",  }],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [{ type: "autogenerated", dirName: "reference",  }],
    },
  ],
  
  sources: [{
    type: "category", 
    label: "Sources",
    collapsible: false,
    items: [{ type: "autogenerated", dirName: "sources",  }],
    link: {
      type: 'generated-index',
    slug: "sources",
    },
  }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
